/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 soulless.gltf
Author: ali-rahimi-shahmirzadi (https://sketchfab.com/ali-rahimi-shahmirzadi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/soulless-1a18f6f206b14073884e1a9c31c03cbc
Title: Soulless
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const gltfLOCATION = 'soulless/soulless.gltf';

export default function Model(props) {
  const { nodes, materials } = useGLTF(gltfLOCATION)
  return (
    <group {...props} dispose={null} >
      <mesh geometry={nodes.Head1Mesh_lambert3_0.geometry} material={materials.lambert3} 
            material-color={'#EEEE9B'} 
      />
      <mesh geometry={nodes.Head1Mesh_lambert3_0_1.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.Head1Mesh_lambert3_0_2.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.Head1Mesh_lambert3_0_3.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.Head1Mesh_lambert3_0_4.geometry} material={materials.lambert3} />
    </group>
  )
}

useGLTF.preload(gltfLOCATION)
