/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 space.gltf
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/need-some-space-d6521362b37b48e3a82bce4911409303
Title: Need some space?
*/

import React from 'react'
import { useGLTF, PointMaterial } from '@react-three/drei'


const gltfLOCATION = 'space/space.gltf';

export default function Space(props) {
  const { nodes, materials } = useGLTF(gltfLOCATION)
  return (
    <group {...props} dispose={null}>
      <points geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={1}>
      <PointMaterial transparent vertexColors size={2} sizeAttenuation={false} depthWrite={false} />
      </points>
    </group>
  )
}

useGLTF.preload(gltfLOCATION)

// export default Space;