/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 thefuture.gltf
Author: Lorenzo Penco (https://sketchfab.com/Eksmanen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/thefuture-b5fda59eb51341a58da234c24074d2f0
Title: TheFuture
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'


const gltfLOCATION = 'thefuture/thefuture.gltf';

export default function Model(props) {
  const { nodes, materials } = useGLTF(gltfLOCATION)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.capelliHIcapelliHIlambert2SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.capelliHIlambert1SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.capelliHIlambert1SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.lambert7SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.lambert7SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.lambert7SG} />
      </group>
    </group>
  )
}

useGLTF.preload(gltfLOCATION)
